import './globals.css'
import { Inter,Noto_Emoji,Lemon } from 'next/font/google'
import { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const noto_emoji = Noto_Emoji({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['emoji']
})

export const lemon = Lemon({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin']
})

const metadata: Metadata = {
  title: 'Splendor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
