import './globals.css'
import { Inter,Noto_Emoji } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const notoEmoji = Noto_Emoji({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['emoji']
})

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
